/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import java.io.IOException;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testCityNameMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.getWeatherByCityName("Melbourne","au"));
    }

    @Test public void testCoordinatesMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.getWeatherByCoordinates("37.81","144.96"));
    }

    @Test public void testZipMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.getWeatherByZip("94040", "us"));
    }
}
