/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Before;
import org.junit.Test;

import java.util.ArrayList;

import static org.junit.Assert.assertNotNull;

public class LibraryTest {
    private Library classUnderTest;

    @Before
    public void initialise() {
        classUnderTest = new Library("53d4ced445dc683d104322a4c8fdb9fc");
    }

    @Test
    public void testCityNameMethod() {
        String response = classUnderTest.getWeatherByCityName("Melbourne", "au");
        assertNotNull("Should return not be null", response);
        System.out.println(response);
    }

    @Test
    public void testCoordinatesMethod() {
        String response = classUnderTest.getWeatherByCoordinates("-37.81", "144.96");
        assertNotNull("Should return not be null", response);
        System.out.println(response);
    }

    @Test
    public void testZipMethod() {
        String response = classUnderTest.getWeatherByZip("94040", "us");
        assertNotNull("Should return not be null", response);
        System.out.println(response);
    }

    @Test
    public void testIDMethod() {
        String response = classUnderTest.getWeatherByCityID("2158177");
        assertNotNull("Should return not be null", response);
        System.out.println(response);
    }

    @Test
    public void testBoxMethod() {
        String response = classUnderTest.getWeatherForCitiesInRectangle("12", "32", "15", "37", "10");
        assertNotNull("Should return not be null", response);
        System.out.println(response);
    }

    @Test
    public void testCircleMethod() {
        String response = classUnderTest.getWeatherForCitiesInCircle("-37.81", "144.96", "10");
        assertNotNull("Should return not be null", response);
        System.out.println(response);
    }

    @Test
    public void testGroupIDMethod() {
        ArrayList<String> idList = new ArrayList<>();
        idList.add("524901");
        idList.add("703448");
        idList.add("2643743");
        String response = classUnderTest.getWeatherForCitiesByID(idList);

        assertNotNull("Should return not be null", response);
        System.out.println(response);
    }
}
